languageCode = "en"
languageName = "English"
weight = 1
title = "Froszyy"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]
  name = "Froszyy"
  image = "img/avatar.png"
  headline = "ヾ(⌒ー⌒)ノ"
  bio = "Unlimited bacon but no games, or games, unlimited games but no games?"
   links = [
     { github = "https://github.com/froszyy" },
     { youtube = "https://www.youtube.com/channel/UCh40De74DC7BYCeVcrxCygQ" },
     { roblox = "https://www.roblox.com/users/589337075/profile" },
     { steam = "https://steamcommunity.com/profiles/76561198837997006/" }
   ]
